-- ============================================
-- PROBLEM STATEMENT
-- ============================================
-- You are a database administrator analyzing customer data.
-- Your goal is to answer questions related to sales, profit, marketing spend,
-- and other business metrics using SQL queries.
-- You will use three key tables: FactTable, ProductTable, and LocationTable.

-- ============================================
-- TABLE STRUCTURES
-- ============================================

-- FactTable (4200 rows, 14 columns)
-- Columns:
-- Date, ProductID, OutletID, Sales, Margin, COGS, Total_Expenses,
-- Marketing, Investment, Budget_Profit, Budget_Margin, Budget_Sales, Mode
-- ProductTable (100 rows)
-- Columns:
-- Product_Type, ProductID, TYPEID

-- LocationTable (156 rows)
-- Columns:
-- Area_Code, State, Market, Market_Size

-- ============================================
-- TASKS TO BE PERFORMED
-- ============================================

-- 1. Display the number of states present in the LocationTable.

	SELECT COUNT(DISTINCT State) FROM Location

-- 2. How many products are of regular type?

	SELECT * FROM Product WHERE Type = 'Regular'

-- 3. How much spending has been done on marketing of product ID 1?

	SELECT SUM(Marketing) FROM Fact WHERE ProductId = 1

-- 4. What is the minimum sales of a product?

	SELECT MIN(Sales) FROM Fact

-- 5. Display the max Cost of Good Sold (COGS).

	SELECT MAX(COGS) FROM Fact

-- 6. Display the details of the product where product type is coffee.

	SELECT * FROM Product WHERE Product_Type = 'Coffee'

-- 7. Display the details where total expenses are greater than 40.

	SELECT * FROM Fact WHERE Total_Expenses > 40

-- 8. What is the average sales in area code 719?

	SELECT AVG(Sales) FROM Fact WHERE Area_Code = 719

-- 9. Find out the total profit generated by Colorado state.

	SELECT SUM(F.Budget_Profit) FROM Fact AS F
	INNER JOIN Location AS L
	ON L.Area_Code = F.Area_Code
	WHERE L.State = 'Colorado'

-- 10. Display the average inventory for each product ID.

	SELECT AVG(Inventory), ProductId FROM Fact GROUP BY ProductId

-- 11. Display state in a sequential order in a Location Table.

	SELECT DISTINCT State FROM Location ORDER BY 1

-- 12. Display the average budget of the Product where the average budget margin should be greater than 100.

	SELECT AVG(
	SELECT * FROM Fact

-- 13. What is the total sales done on date 2010-01-01?

-- 14. Display the average total expense of each product ID on an individual date.

-- 15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

-- 16. Display the rank without any gap to show the sales wise rank. (DENSE_RANK)

-- 17. Find the state wise profit and sales.

-- 18. Find the state wise profit and sales along with the product name.

-- 19. If there is an increase in sales of 5%, calculate the increasedSales.

-- 20. Find the maximum profit along with the product ID and product type.

-- 21. Create a stored procedure to fetch the result according to the product type from Product Table.

-- 22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.

-- 23. Give the total weekly sales value with the date and product ID details. Use roll-up to pull the data in hierarchical order.

-- 24. Apply union and intersection operator on the tables which consist of attribute area code.

-- 25. Create a user-defined function for the product table to fetch a particular product type based upon the user's preference.

-- 26. Change the product type from coffee to tea where product ID is 1 and undo it.

-- 27. Display the date, product ID and sales where total expenses are between 100 to 200.

-- 28. Delete the records in the Product Table for regular type.

-- 29. Display the ASCII value of the fifth character from the column Product.
